#Panel Identification
std_msgs/String panel_location



#Button Status
std_msgs/Bool btn1
std_msgs/Bool btn2
std_msgs/Bool btn3
std_msgs/Bool btn4
std_msgs/Bool btn5
std_msgs/Bool btn6
std_msgs/Bool btn7
std_msgs/Bool btn8
std_msgs/Bool btn9
std_msgs/Bool btn10
std_msgs/Bool btn11
std_msgs/Bool btn12
std_msgs/Bool btn13
std_msgs/Bool btn14
std_msgs/Bool btn15
std_msgs/Bool btn16
std_msgs/Bool btn17
std_msgs/Bool btn18
std_msgs/Bool btn19
std_msgs/Bool btn20
std_msgs/Bool btn21